# Generated by Django 4.2.20 on 2025-04-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('img', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('starred', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('parent_id', models.IntegerField(blank=True, default=None, null=True)),
                ('children_id', models.JSONField(default=list)),
            ],
        ),
    ]
