# Generated by Django 5.2 on 2025-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='bid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
