# Generated by Django 5.2.1 on 2025-05-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='bid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='treestructure',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_structures', to='api.user'),
        ),
        migrations.AlterField(
            model_name='treestructure',
            name='bid',
            field=models.ForeignKey(db_column='bid_id', on_delete=django.db.models.deletion.CASCADE, related_name='tree_structures', to='api.bookmarks'),
        ),
        migrations.AlterField(
            model_name='treestructure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treestructure',
            name='parent_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarks',
            unique_together={('account', 'bid')},
        ),
        migrations.AlterUniqueTogether(
            name='treestructure',
            unique_together={('account', 'bid')},
        ),
        migrations.AlterModelTable(
            name='treestructure',
            table='api_treestructure',
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
