# Generated by Django 4.2.20 on 2025-04-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='children_id',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
