# Generated by Django 5.2 on 2025-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookmarks_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treestructure',
            name='parent_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
