# Generated by Django 4.2.20 on 2025-04-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookmarks_children_id_alter_bookmarks_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
