# Generated by Django 4.2.20 on 2025-04-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_databasestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasestatus',
            name='lastUpdated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
