# Generated by Django 4.2.20 on 2025-04-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_databasestatus_lastupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasestatus',
            name='id',
        ),
        migrations.AddField(
            model_name='databasestatus',
            name='sid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
