version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"  # Vite 預設端口
    volumes:
      - ./frontend:/app/frontend  # Bind local source files to container
      - /app/frontend/node_modules  # Prevent local node_modules from overwriting container's

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Django 預設端口
    volumes:
      - ./backend:/app