services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: team15-frontend
    ports:
      - "5174:5174"
    volumes:
      - ../frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: team15-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../.env
    environment:
      - DB_TYPE=mariadb
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:11.7-ubi9
    container_name: db
    environment:
      MYSQL_DATABASE: bookmarks
      MYSQL_USER: team15
      MYSQL_ROOT_PASSWORD: '16'
      MYSQL_PASSWORD: '16'
    ports:
      - "3306:3306"
    volumes:
      - ../mariadb:/var/lib/mysql  # Persist database data
    healthcheck:
      test: ["CMD-SHELL", "mysql -u team15 -p16 -e 'SELECT 1;'"]
      interval: 6s
      timeout: 3s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      PMA_HOST: db
      PMA_USER: team15
      PMA_PASSWORD: '16'
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy