// 先用這個檔案來模擬資料庫的功能，之後再改成真正的資料庫
export const treeStructure = {
  0: { parent_id: null, children_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
  1: { parent_id: 0, children_id: [] },
  2: { parent_id: 0, children_id: [] },
  3: { parent_id: 0, children_id: [] },
  4: { parent_id: 0, children_id: [] },
  5: { parent_id: 0, children_id: [] },
  6: { parent_id: 0, children_id: [] },
  7: { parent_id: 0, children_id: [] },
  8: { parent_id: 0, children_id: [] },
  9: { parent_id: 0, children_id: [] },
  10: { parent_id: 0, children_id: [14, 15, 16, 17] },
  11: { parent_id: 0, children_id: [18] },
  12: { parent_id: 0, children_id: [13] },
  13: { parent_id: 12, children_id: [] },
  14: { parent_id: 10, children_id: [] },
  15: { parent_id: 10, children_id: [] },
  16: { parent_id: 10, children_id: [] },
  17: { parent_id: 10, children_id: [] },
  18: { parent_id: 11, children_id: [] },
};

export const idToBookmark = {
  0: {
    id: 0,
    url: "#",
    img: "folder.png",
    name: "Home",
    tags: [],
    starred: false,
    hidden: false,
  },
  1: {
    id: 1,
    url: "https://chatgpt.com/",
    img: "GPT.ico",
    name: "ChatGPT",
    tags: ["AI", "tool"],
    starred: true,
    hidden: false,
  },
  2: {
    id: 2,
    url: "https://claude.ai/",
    img: "claude.png",
    name: "Claude",
    tags: ["AI", "tool"],
    starred: false,
    hidden: false,
  },
  3: {
    id: 3,
    url: "https://www.gamer.com.tw/index2.php",
    img: "baha.svg",
    name: "巴哈姆特",
    tags: ["game", "community"],
    starred: false,
    hidden: false,
  },
  4: {
    id: 4,
    url: "https://mail.google.com/",
    img: "gmail.ico",
    name: "Gmail",
    tags: ["email"],
    starred: true,
    hidden: false,
  },
  5: {
    id: 5,
    url: "https://outlook.office365.com/",
    img: "outlook.ico",
    name: "Outlook",
    tags: ["email"],
    starred: true,
    hidden: false,
  },
  6: {
    id: 6,
    url: "https://www.ntu.edu.tw/",
    img: "NTU.png",
    name: "NTU",
    tags: ["學校"],
    starred: false,
    hidden: false,
  },
  7: {
    id: 7,
    url: "https://www.youtube.com/",
    img: "YT.ico",
    name: "YouTube",
    tags: ["影音"],
    starred: false,
    hidden: false,
  },
  8: {
    id: 8,
    url: "https://www.netflix.com/tw/",
    img: "nficon2023.ico",
    name: "Netflix",
    tags: ["影音"],
    starred: false,
    hidden: false,
  },
  9: {
    id: 9,
    url: "https://www.ruten.com.tw/",
    img: "露天.ico",
    name: "露天拍賣",
    tags: ["電商"],
    starred: false,
    hidden: false,
  },
  10: {
    id: 10,
    url: "#",
    img: "folder.png",
    name: "Papers",
    tags: ["Paper"],
    starred: true,
    hidden: false,
  },
  11: {
    id: 11,
    url: "#",
    img: "folder.png",
    name: "Linux",
    tags: ["Linux"],
    starred: true,
    hidden: false,
  },
  12: {
    id: 12,
    url: "#",
    img: "folder.png",
    name: "Web",
    tags: ["Web"],
    starred: true,
    hidden: false,
  },
  13: {
    id: 13,
    url: "https://fonts.google.com/icons?source=sh%2Fx%2Fsrp%2Fwr%2Fm1%2F4&kgs=8ea543ccb9457f88",
    img: "fonts.png",
    name: "Google Icons",
    tags: ["Web"],
    starred: false,
    hidden: false,
  },
  14: {
    id: 14,
    url: "https://academic.oup.com/bioinformatics/issue/40/1",
    img: "Oxford.jpg",
    name: "Bioinformatics",
    tags: ["Paper"],
    starred: false,
    hidden: false,
  },
  15: {
    id: 15,
    url: "https://academic.oup.com/bioinformatics/issue/40/1",
    img: "CVPR.png",
    name: "CVPR",
    tags: ["Paper"],
    starred: false,
    hidden: false,
  },
  16: {
    id: 16,
    url: "https://academic.oup.com/bioinformatics/issue/40/1",
    img: "ICLR.jpg",
    name: "ICLR",
    tags: ["Paper"],
    starred: false,
    hidden: false,
  },
  17: {
    id: 17,
    url: "https://academic.oup.com/bioinformatics/issue/40/1",
    img: "Elsevier.jpg",
    name: "MIA",
    tags: ["Paper"],
    starred: false,
    hidden: false,
  },
  18: {
    id: 18,
    url: "https://linux.vbird.org/",
    img: "bird.jpg",
    name: "鳥哥的Linux",
    tags: ["Linux"],
    starred: false,
    hidden: false,
  },
};
