// 先用這個檔案來模擬資料庫的功能，之後再改成真正的資料庫
export const treeStructure = {
    0: { parent_id: null, children_id: [1, 2, 3, 4, 5, 6, 7, 10, 11] },
    1: { parent_id: 0, children_id: [] },
    2: { parent_id: 0, children_id: [] },
    3: { parent_id: 0, children_id: [] },
    4: { parent_id: 0, children_id: [] },
    5: { parent_id: 0, children_id: [] },
    6: { parent_id: 0, children_id: [] },
    7: { parent_id: 0, children_id: [] },
    10: { parent_id: 0, children_id: [8, 9] },
    8: { parent_id: 10, children_id: [] },
    9: { parent_id: 10, children_id: [] },
    11: { parent_id: 0, children_id: [] },
  };
  
  export const idToBookmark = {
    1: {
      id: 1,
      url: "https://chatgpt.com/",
      img: "GPT.ico",
      name: "ChatGPT",
      tags: ["AI", "tool"],
      starred: true,
      hidden: false,
    },
    2: {
      id: 2,
      url: "https://claude.ai/",
      img: "claude.png",
      name: "Claude",
      tags: ["AI", "tool"],
      starred: false,
      hidden: false,
    },
    3: {
      id: 3,
      url: "https://www.gamer.com.tw/index2.php",
      img: "baha.svg",
      name: "巴哈姆特",
      tags: ["game", "community"],
      starred: false,
      hidden: false,
    },
    4: {
      id: 4,
      url: "https://mail.google.com/",
      img: "gmail.ico",
      name: "Gmail",
      tags: ["email"],
      starred: true,
      hidden: false,
    },
    5: {
      id: 5,
      url: "https://outlook.office365.com/",
      img: "outlook.ico",
      name: "Outlook",
      tags: ["email"],
      starred: true,
      hidden: false,
    },
    6: {
      id: 6,
      url: "https://www.ntu.edu.tw/",
      img: "NTU.png",
      name: "NTU",
      tags: ["學校"],
      starred: false,
      hidden: false,
    },
    7: {
      id: 7,
      url: "https://www.youtube.com/",
      img: "YT.ico",
      name: "YouTube",
      tags: ["影音"],
      starred: false,
      hidden: false,
    },
    8: {
      id: 8,
      url: "https://www.netflix.com/tw/",
      img: "nficon2023.ico",
      name: "Netflix",
      tags: ["影音"],
      starred: false,
      hidden: false,
    },
    9: {
      id: 9,
      url: "https://www.ruten.com.tw/",
      img: "露天.ico",
      name: "露天拍賣",
      tags: ["電商"],
      starred: false,
      hidden: false,
    },
    10: {
      id: 10,
      url: "#",
      img: "folder.png",
      name: "Docker",
      tags: ["Docker"],
      starred: true,
      hidden: false,
    },
    11: {
      id: 11,
      url: "#",
      img: "folder.png",
      name: "Linux",
      tags: ["Linux"],
      starred: true,
      hidden: false,
    },
  };
  